language: php

php:
    - 7.0
    - 7.1
    - 7.2

env:
  - COMPOSER_OPTIONS="--prefer-source"
  - COMPOSER_OPTIONS="--prefer-source --prefer-lowest"

before_script:
    - phpenv config-rm xdebug.ini
    - composer update $COMPOSER_OPTIONS

notifications:
  email: false
